name: "go package reader"
description: "outputs the package.json version"

inputs:
  path:
    description: "path of package.json"
    default: "./"

outputs:
  version:
    description: "version of package"

# runs:
#   using: "node20"
#   main: "dist/index.js"
runs:
  using: docker
  image: Dockerfile
  # args:
  #   - ${{ inputs.path }}
  env: 
    ACTION_INPUT: ${{ inputs.path }}
  entrypoint: "entrypoint.sh"

branding:
  icon: 'activity'
  color: 'green'