name: Go

# on: [push]
on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x', '1.22.x' ]

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

     
      - name: unit test
        run: go test

      # - name: get version
      #   run: 